config/routes.rb
Rails.application.routes.draw do
  get "register/new"
  get "register/create"

  devise_for :trainers

  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :cards
  resources :card_packs

  resources :trainer, only: [] do
    resources :cards, only: [:index, :create]
  end
end

app/views/layouts/_navbar.html.erb
<div class="navbar bg-base-100 justify-end">
  <div class="flex-1">
    <%= link_to "Pokemania", root_path, class: "btn btn-ghost normal-case text-xl" %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal gap-2 px-1">
      <% if trainer_signed_in? %>
        <li><%= link_to "Collection", trainer_cards_path(current_trainer), class: ("active" if current_page?(trainer_cards_path(current_trainer))) %></li>
      <% end %>
      <li><%= link_to "Store", card_packs_path, class: ("active" if current_page?(card_packs_path)) %></li>
      <li><%= link_to "Cards", cards_path, class: ("active" if current_page?(cards_path)) %></li>
      <% if trainer_signed_in? %>
        <%= link_to "Sign out", destroy_trainer_session_path, method: :delete, data: { turbo_method: :delete }, class: "btn" %>
      <% else %>
        <%= link_to "Sign in", new_trainer_session_path, class: "btn" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="night">
  <head>
    <title>TcgPokemon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col h-screen">
    <header>
      <%= render "layouts/navbar" %>
    </header>

    <main class="container mb-auto mx-auto mt-5 px-5 md:w-2/3">
      <%= yield %>
    </main>

    <footer class="footer footer-center p-4 bg-base-300 text-base-content">
      <div>
        <p>Copyright © 2023 - Peter de Ridder</p>
      </div>
    </footer>
  </body>
</html>